{{- include "factory.headers" . }}
{{- if .Values.global }}
---
{{ include "factory.pvConfigCommonSpec" . }}
  storageClassName: manual
  hostPath:
    path: {{ .Values.global.storage.hostPath.path }}/isecl/{{ .Values.service.directoryName }}/config
{{- else }}
---
{{ include "factory.pvConfigCommonSpec" . }}
  storageClassName: manual
  hostPath:
    path: {{ .Values.storage.hostPath.path }}/isecl/{{ .Values.service.directoryName }}/config
{{- end }}
