{{- include "factory.headers" . }}
{{- if .Values.global }}
---
{{ include "factory.pvConfigCommonSpec" . }}
  storageClassName: manual
  hostPath:
    path: {{ .Values.global.hostPath.nfs.path }}/isecl/hvs/config
{{- else }}
---
{{ include "factory.pvConfigCommonSpec" . }}
  storageClassName: manual
  hostPath:
    path: {{ .Values.storage.hostPath.path }}/isecl/hvs/config
{{- end }}
